### ISSUE TITLE
Add Option to see user Profile 

### ISSUE THREAD

**Issue by bitaashna** [ALPHAVIO/BlogSite#230] opened 2021-03-07 12:23 UTC
Currently the app is missing the option of user profile

Adding an option to see user profile in the home page.
In the profile option user can see user image, username and his/her email.
I would like to contribute to it as a part of GSSOC'21.
Can you please assign it to me.

**Comment by micksharma** [comment] 2021-03-08 19:38
Cai I work on this issue ?

**Comment by micksharma** [comment] 2021-03-08 19:39
Can I work on this issue ?

**Comment by abhinav5481** [comment] 2021-03-09 04:24
I would like to work on this issue. Could you please assign it to me?

**Comment by Esha-Sherring** [comment] 2021-03-09 08:26
I would like to work on this issue

**Comment by machine-sg** [comment] 2021-03-10 11:14
I want to work on this as a part of GSSOC'21 .

**Comment by shudhanshu03** [comment] 2021-03-11 20:12
/level3/

**Comment by AnanyaNegi** [comment] 2021-03-12 06:13
@bitaashna are you still working on this issue?

**Comment by bitaashna** [comment] 2021-03-12 06:43
yea @AnanyaNegi ,I am working on it. By tomorrow I'll submit it.

**Comment by shamadevi** [comment] 2021-03-23 05:10
Can I work on this issue ?

**Comment by RushanKhan1** [comment] 2021-03-23 13:32
@shamadevi Sure, the issue is yours.

**Comment by Pranav016** [comment] 2021-03-27 11:03
functionality is already there..

**Closed by Pranav016** 2021-03-27 11:03 UTC
Labels: GSSOC21, Level3, slash-assigned
