### ISSUE TITLE
Improve Dark mode color combinations

### ISSUE THREAD

**Issue by GuptaTanisha** [ALPHAVIO/BlogSite#317] opened 2021-03-13 01:24 UTC
### Feature request-
To improve the color combinations of dark mode.

### Describe the solution you'd like
I will improve the color combinations.

### Describe how this feature will be useful to our readers.
A better UI facilitates the reading experience.

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
* If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
*  According to the **level** of the issue, respective ***time*** will be allotted under which the task needs to be completed/resolved by the assigned person. If the issue is not resolved within the given time, it will be assigned to the next person. In case of any discrepancies, the decision of the maintainer will be final.
```
level0- 2 days
level1- 3 days
level2- 4 days
level3- 5 days
```

**Comment by Pranav016** [comment] 2021-03-13 09:33
/gssoc/

**Comment by Pranav016** [comment] 2021-03-13 09:33
/level2/

**Comment by RushanKhan1** [comment] 2021-03-17 06:54
Hey @GuptaTanisha, It's been 4 days since you were assigned the issue. Are you still working on it?

**Comment by vismitap** [comment] 2021-03-17 18:23
May I work on this issue as a part of GSSoC'21?

**Comment by RushanKhan1** [comment] 2021-03-20 17:22
@vismitap Okay, since @GuptaTanisha didn't respond with her status, the issue is yours to work with, good luck!

**Comment by RushanKhan1** [comment] 2021-03-26 13:56
@vismitap Hey, what's the status?

**Comment by vismitap** [comment] 2021-03-26 14:01
> @vismitap Hey, what's the status?

Hey sorry! I was busy with exams and submissions so could not get time. Please allow me 1 more day. Will fix this by tomorrow! 😅

**Comment by vismitap** [comment] 2021-03-28 14:13
@Pranav016 @RushanKhan1 I am very confused about the project and its deployment actually. 
1) I had contributed to this project earlier also. I had added the like feature which was merged but now it is nowhere to be seen. There's a new issue to add the likes counter. 
2) The view of the website for me after pulling the latest changes is this (old design dark mode in localhost):
![image](https://user-images.githubusercontent.com/47056243/112755225-62156800-8ffd-11eb-95d7-68d1363431ec.png)
and now its like this (on heroku):
![image](https://user-images.githubusercontent.com/47056243/112755263-87a27180-8ffd-11eb-9318-c40bb902675d.png)
   
Why am I not able to view the new design even after pulling latest changes? Was this issue made to change the old dark mode combination?

**Comment by Pranav016** [comment] 2021-03-28 14:18
> @Pranav016 @RushanKhan1 I am very confused about the project and its deployment actually.
> 
> 1. I had contributed to this project earlier also. I had added the like feature which was merged but now it is nowhere to be seen. There's a new issue to add the likes counter.
> 2. The view of the website for me after pulling the latest changes is this (old design dark mode in localhost):
>    ![image](https://user-images.githubusercontent.com/47056243/112755225-62156800-8ffd-11eb-95d7-68d1363431ec.png)
>    and now its like this (on heroku):
>    ![image](https://user-images.githubusercontent.com/47056243/112755263-87a27180-8ffd-11eb-9318-c40bb902675d.png)
> 
> Why am I not able to view the new design even after pulling latest changes? Was this issue made to change the old dark mode combination?

When your like feature was merged or some other PR that was merged along with it had bugs and caused website to crash so I reverted the commits..

**Comment by Pranav016** [comment] 2021-03-28 14:20
I think this is a very old issue, we had a new theme added to the website after this.
Closing issue, reopen or re-raise if required

**Comment by Pranav016** [comment] 2021-03-28 14:20
I think this is a very old issue, we had a new theme added to the website after this.
Closing issue, reopen or re-raise if required

**Comment by vismitap** [comment] 2021-03-28 14:21
> > @Pranav016 @RushanKhan1 I am very confused about the project and its deployment actually.
> > 
> > 1. I had contributed to this project earlier also. I had added the like feature which was merged but now it is nowhere to be seen. There's a new issue to add the likes counter.
> > 2. The view of the website for me after pulling the latest changes is this (old design dark mode in localhost):
> >    ![image](https://user-images.githubusercontent.com/47056243/112755225-62156800-8ffd-11eb-95d7-68d1363431ec.png)
> >    and now its like this (on heroku):
> >    ![image](https://user-images.githubusercontent.com/47056243/112755263-87a27180-8ffd-11eb-9318-c40bb902675d.png)
> > 
> > Why am I not able to view the new design even after pulling latest changes? Was this issue made to change the old dark mode combination?
> 
> When your like feature was merged or some other PR that was merged along with it had bugs and caused website to crash so I reverted the commits..

Okay but now I have pulled the latest code, still not able to view the new design on localhost. Please help me with this!

**Closed by Pranav016** 2021-03-28 14:20 UTC
Labels: GSSOC21, Level2, slash-assigned

**Comment by Pranav016** [comment] 2021-03-28 14:22
> @Pranav016 @RushanKhan1 I am very confused about the project and its deployment actually.
> 
> 1. I had contributed to this project earlier also. I had added the like feature which was merged but now it is nowhere to be seen. There's a new issue to add the likes counter.
> 2. The view of the website for me after pulling the latest changes is this (old design dark mode in localhost):
>    ![image](https://user-images.githubusercontent.com/47056243/112755225-62156800-8ffd-11eb-95d7-68d1363431ec.png)
>    and now its like this (on heroku):
>    ![image](https://user-images.githubusercontent.com/47056243/112755263-87a27180-8ffd-11eb-9318-c40bb902675d.png)
> 
> Why am I not able to view the new design even after pulling latest changes? Was this issue made to change the old dark mode combination?

Should work fine if you pulled it from master.

 your remote might not be set correctly. Maybe you are pulling from forked repo
